"""Current public API for the v2.4 standalone vehicle reference package.

Historical closeout modules remain available by their qualified module paths
for provenance and regression, but are not re-exported here as current API.
"""

from .engine_model import (
    DomainError,
    EngineAsset,
    EngineCommand,
    EngineMode,
    EngineModel,
    EngineOwner,
    EngineState,
    TorqueSemantics,
    rad_s_to_rpm,
    rpm_to_rad_s,
)
from .coupled_vehicle_solver import (
    Axle,
    ClutchMode,
    CoupledSolveError,
    CoupledVehicleConfig,
    CoupledVehicleState,
    CoupledVehicleStepResult,
    EngineBoundMode,
    TireMode,
    SolverModeHint,
    mode_hint_from_result,
    solve_coupled_vehicle_substep,
)
from .runtime_vehicle_solver import solve_runtime_coupled_vehicle_substep
from .powertrain_controller import (
    GearDefinition,
    GearboxAsset,
    GearboxCommand,
    GearboxState,
    PowertrainTransactionAudit,
    PowertrainVehicleState,
    PowertrainVehicleSystem,
    ShiftPhase,
    SubstepSplitRequired,
    ideal_open_differential_mapping,
)
from .asset_pipeline import (
    AssetCompileError,
    EngineAssetCompiler,
    verify_compiled_engine_bundle,
)
from .timeseries_pipeline import (
    MissingDataPolicy,
    SignalChannel,
    TimeSeriesImportSpec,
    TimeSeriesProcessor,
)
from .host_integration import (
    StandalonePowertrainAdapter,
    SubstepRequest,
    SubstepResponse,
)
from .unified_vehicle_fixture import (
    BrakeRegime,
    ContactRegime,
    RigidBodyDynamicsHostRequired,
    ClutchRegime,
    CornerEvaluation,
    DriverControlledStepResult,
    MechanicalState,
    SteeringCausality,
    SuspensionBackend,
    TransactionAudit,
    UnifiedDomainError,
    UnifiedSolveError,
    UnifiedVehicleCommand,
    UnifiedVehicleConfig,
    UnifiedVehicleFixture,
    UnifiedVehicleState,
    UnifiedVehicleStepResult,
)
from .accepted_tire_adapter import (
    FrictionContactHostRequired,
    TireModel as AcceptedTireModel,
    TireState as AcceptedTireState,
    make_reference_model as make_accepted_tire_model,
)
from .tire_host_contract import (
    AdaptedContact,
    ContactInput,
    FinalContactKinematics,
    SuspensionContactPacket,
    VerticalLawOutput,
    adapt_contact,
)
from .vehicle_controls_reference import (
    AssistEvaluation,
    BrakeAssistConfig,
    BrakeAssistController,
    DirectionFSMConfig,
    DirectionFSMState,
    DirectionFSMTrial,
    DriverCommand,
    DriverDirectionFSM,
    RequestedDirection,
)

__all__ = [
    "DomainError",
    "EngineAsset",
    "EngineCommand",
    "EngineMode",
    "EngineModel",
    "EngineOwner",
    "EngineState",
    "TorqueSemantics",
    "rad_s_to_rpm",
    "rpm_to_rad_s",
    "Axle",
    "ClutchMode",
    "CoupledSolveError",
    "CoupledVehicleConfig",
    "CoupledVehicleState",
    "CoupledVehicleStepResult",
    "EngineBoundMode",
    "TireMode",
    "SolverModeHint",
    "mode_hint_from_result",
    "solve_coupled_vehicle_substep",
    "solve_runtime_coupled_vehicle_substep",
    "GearDefinition",
    "GearboxAsset",
    "GearboxCommand",
    "GearboxState",
    "PowertrainTransactionAudit",
    "PowertrainVehicleState",
    "PowertrainVehicleSystem",
    "ShiftPhase",
    "SubstepSplitRequired",
    "ideal_open_differential_mapping",
    "AssetCompileError",
    "EngineAssetCompiler",
    "verify_compiled_engine_bundle",
    "MissingDataPolicy",
    "SignalChannel",
    "TimeSeriesImportSpec",
    "TimeSeriesProcessor",
    "StandalonePowertrainAdapter",
    "SubstepRequest",
    "SubstepResponse",
    "BrakeRegime",
    "ContactRegime",
    "RigidBodyDynamicsHostRequired",
    "ClutchRegime",
    "CornerEvaluation",
    "DriverControlledStepResult",
    "MechanicalState",
    "SteeringCausality",
    "SuspensionBackend",
    "TransactionAudit",
    "UnifiedDomainError",
    "UnifiedSolveError",
    "UnifiedVehicleCommand",
    "UnifiedVehicleConfig",
    "UnifiedVehicleFixture",
    "UnifiedVehicleState",
    "UnifiedVehicleStepResult",
    "FrictionContactHostRequired",
    "AcceptedTireModel",
    "AcceptedTireState",
    "make_accepted_tire_model",
    "AdaptedContact",
    "ContactInput",
    "FinalContactKinematics",
    "SuspensionContactPacket",
    "VerticalLawOutput",
    "adapt_contact",
    "AssistEvaluation",
    "BrakeAssistConfig",
    "BrakeAssistController",
    "DirectionFSMConfig",
    "DirectionFSMState",
    "DirectionFSMTrial",
    "DriverCommand",
    "DriverDirectionFSM",
    "RequestedDirection",
]
