import bpy,math,json,pathlib
from mathutils import Vector
root=pathlib.Path('/Volumes/Storage/streetrush');bpy.ops.wm.read_factory_settings(use_empty=True);bpy.ops.import_scene.gltf(filepath=str(root/'scratch/pit-game-preview-20260907/tree-source/jacaranda_tree_1k.gltf'))
objs=[o for o in bpy.data.objects if o.type=='MESH'];points=[o.matrix_world@Vector(p) for o in objs for p in o.bound_box];lo=Vector([min(p[i] for p in points) for i in range(3)]);hi=Vector([max(p[i] for p in points) for i in range(3)]);center=(lo+hi)/2
world=bpy.data.worlds.new('Soft outdoor illumination');world.use_nodes=True;bg=world.node_tree.nodes.new('ShaderNodeBackground');bg.inputs[0].default_value=(.65,.75,.85,1);bg.inputs[1].default_value=.65;out=world.node_tree.nodes.new('ShaderNodeOutputWorld');world.node_tree.links.new(bg.outputs[0],out.inputs['Surface']);bpy.context.scene.world=world
light=bpy.data.lights.new('Sun','SUN');light.energy=2.4;ob=bpy.data.objects.new('Sun',light);bpy.context.collection.objects.link(ob);ob.rotation_euler=(.5,-.4,-.7)
camera=bpy.data.cameras.new('Camera');camera.type='ORTHO';camera.ortho_scale=max(hi.x-lo.x,hi.y-lo.y,hi.z-lo.z)*1.08;ob=bpy.data.objects.new('Camera',camera);bpy.context.collection.objects.link(ob)
s=bpy.context.scene;s.camera=ob;s.render.engine='CYCLES';s.cycles.samples=16;s.cycles.use_denoising=True;s.render.threads_mode='FIXED';s.render.threads=4;s.render.resolution_x=1024;s.render.resolution_y=1024;s.render.resolution_percentage=100;s.render.film_transparent=True;s.render.image_settings.file_format='PNG';s.render.image_settings.color_mode='RGBA';s.view_settings.view_transform='Standard';s.view_settings.look='None';s.view_settings.exposure=-.5
for i,angle in enumerate([0,1.2]):
 ob.location=center+Vector((math.sin(angle)*60,-math.cos(angle)*60,1));ob.rotation_euler=(center-ob.location).to_track_quat('-Z','Y').to_euler();s.render.filepath=str(root/f'public/scenery/longwan/textures/tree-{i}.png');bpy.ops.render.render(write_still=True)
(root/'scratch/pit-game-preview-20260907/tree-sprite.json').write_text(json.dumps({'source':'https://polyhaven.com/a/jacaranda_tree','license':'CC0-1.0','author':'Rico Cilliers; Rob Tuytel','method':'Two orthographic transparent renders of source model; distant crossed-card foliage only','size':1024,'bounds':[list(lo),list(hi)]},indent=2));print('TREE_SPRITES_COMPLETE',flush=True)
