import fs from 'node:fs/promises';
import crypto from 'node:crypto';
const source='scratch/lighting-basics-20260907',out='docs/verification/lighting-basics-20260907';
await fs.mkdir(out,{recursive:true});
for(const name of ['barrier-before.png','barrier-after.png','car-before.png','car-after.png','indirect-before.png','indirect-after.png','coated-indirect-before.png','coated-indirect-after.png','colour-bounce-before.png','colour-bounce-after.png','diffuse-probes.json','colour-bounce-probes.json','performance-indirect-off.json','performance-indirect-on.json','performance-before.json','performance-after.json','performance-before-repeat.json'])await fs.copyFile(`${source}/${name}`,`${out}/${name}`);
const hashes={};
for(const name of ['src/rendering.js','src/render-review.js','src/dev-diffuse-probe-review.js','src/car-materials.js','src/assets.js'])hashes[name]=crypto.createHash('sha256').update(await fs.readFile(name)).digest('hex');
await fs.writeFile(`${out}/source-sha256.json`,JSON.stringify(hashes,null,2));
await fs.writeFile(`${out}/index.html`, `<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>StreetRush · 护栏基础光照对比</title><style>
:root{color-scheme:dark;font-family:system-ui;background:#11191f;color:#e9eef2}body{max-width:1280px;margin:24px auto;padding:0 20px 48px}h1{font-size:26px}p{color:#b8c5cf;line-height:1.7}button,a{color:#e0ed92}button{background:#253440;border:1px solid #52636f;padding:10px 16px;border-radius:7px;cursor:pointer;margin:0 8px 14px 0}.compare{aspect-ratio:16/9;position:relative;overflow:hidden;border:1px solid #52636f;border-radius:8px;--split:50%}.compare img{position:absolute;width:100%;height:100%;object-fit:fill}.before{clip-path:inset(0 calc(100% - var(--split)) 0 0)}.line{position:absolute;left:var(--split);height:100%;width:2px;background:white}.tag{position:absolute;top:12px;padding:8px;background:#111a22dd;border-radius:6px}.old{left:12px}.new{right:12px}input{width:100%;accent-color:#d9ec91}table{border-collapse:collapse;width:100%}td,th{border-bottom:1px solid #43515b;padding:10px;text-align:left}small{color:#aebac4}</style>
<p style="padding:14px;border:1px solid #b58a58;background:#30261e;color:#f0d4ad"><strong>未采用的历史实验。</strong> 用户视觉验收未通过，已撤出开发检查入口；这不是当前效果方案。<a href="../../LIGHTING_CURRENT_STATE.md">查看当前状态整理</a></p><h1>阴影里的反弹光 · 局部实机验证</h1><p>现有赛道、同机位 1280×720 原始 Canvas 帧。先验证周围颜色确实能进入护栏暗部，再判断正常场景下的改善是否值得保留。</p>
<button id="colour-bounce">颜色反弹验证</button><button id="coated-indirect">正常地面／涂漆护栏</button><button id="indirect">原护栏材质</button><button id="barrier">基础投影</button><button id="car">车辆投影</button><div id="compare" class="compare"><img id="after" src="colour-bounce-after.png" alt="开启局部间接光"><img id="before" class="before" src="colour-bounce-before.png" alt="关闭局部间接光"><div class="line"></div><span class="tag old">之前／关闭</span><span class="tag new">现在／开启</span></div><input id="split" aria-label="拖动比较前后" type="range" min="0" max="100" value="50">
<p>颜色验证组中，橙色色板和护栏材质在两张图中完全一致，只开关局部间接光；没有把护栏颜色改成橙色。色板是开发测试物体，没有加入正常赛道。此组和“正常地面”组采用临时涂层材质（metalness 0.02、roughness 0.72）；“原护栏材质”组保留原值 0.72 / 0.38。三组用途不同，不能混为一次原版／新版比较。</p>
<p>方法：在护栏附近的低处和高处，用两次 32×32 立方体捕获记录已受光场景，转成球谐光照样本。在有限区域内替换统一的漫反射环境补光，并按高度混合；保留原有镜面环境反射。采样后不逐帧捕获，也不增加渲染 pass。它是局部、静态、低频近似，存在颜色扩散过宽、空间遮挡不足的限制；尚未接入全赛道，不能称为完整 GI。<a href="https://threejs.org/docs/pages/LightProbeGenerator.html">Three.js 光照探针生成器</a></p>
<h2>局部间接光成本</h2><p>同机位正常地面、临时涂漆护栏、无色板。M4 / 1280×720，每组 3 秒预热、12 秒采样，正常比赛模拟，静态阴影缓存。两个配置都保留同一套开发着色器。</p><table><tr><th>指标</th><th>关闭</th><th>开启</th></tr><tr><td>GPU 平均 ms</td><td>2.920</td><td>2.987</td></tr><tr><td>GPU P95 ms</td><td>3.812</td><td>3.851</td></tr><tr><td>绘制次数</td><td>66</td><td>66</td></tr></table><p>此局部样例约增加 0.067 ms GPU；不包括一次性采样时间，也不代表全赛道、未注入开发着色器的生产基线或手机成本。<a href="performance-indirect-off.json">关闭统计</a> · <a href="performance-indirect-on.json">开启统计</a></p>
<h2>已经接入的基础投影修正</h2>
<p>原太阳接近顺着起点护栏照射，内侧地面投影不突出。现在改为斜横向照射，护栏分段投影落到赛道内侧。阴影图从 56 m 覆盖扩到 112 m，并向车辆前方移动 24 m。仍使用一张原分辨率阴影图；偏移随阴影像素尺寸调整。没有通过压黑整个场景制造对比。</p>
<p>正常游戏目前接入的是太阳投影与明暗关系修正。局部间接光、色板、临时护栏涂层均仅存在于开发小样。护栏几何、车辆材质文件未修改。车身细纹在开发诊断中关闭太阳投影或 AO 后仍可见，本次未处理其材质／几何来源。</p>
<h2>短性能对照</h2><p>Apple M4，固定 1280×720，GT3 可见、同机位，正常比赛模拟。开发工具强制每个渲染帧更新太阳阴影，避免用静态阴影缓存掩盖覆盖范围的成本。各组预热 3 秒、采样 12 秒。</p>
<table><tr><th>配置</th><th>GPU 平均 / 中位 ms</th><th>GPU P95 ms</th><th>绘制次数</th></tr><tr><td>原配置首次</td><td>10.924 / 11.189</td><td>15.457</td><td>268</td></tr><tr><td>修正配置</td><td>4.455 / 4.450</td><td>4.990</td><td>274</td></tr><tr><td>原配置补充</td><td>10.866 / 4.706</td><td>34.218</td><td>268</td></tr></table>
<p>原配置两次结果有明显调度／本机负载波动，因此不能把新版较低耗时解释为优化收益，尚无法可靠量化 GPU 增量。能确认该机位多了 6 次阴影绘制，阴影贴图尺寸与数量未增加。真实手机与长期驾驶未测。</p><p><a href="performance-before.json">首次原配置</a> · <a href="performance-after.json">修正配置</a> · <a href="performance-before-repeat.json">补充原配置</a> · <a href="source-sha256.json">源码校验和</a></p>
<p><a href="http://127.0.0.1:5173/?renderreview&reviewcar=gt3rs&reviewview=barrier">打开 5 FPS 护栏实机</a> · <a href="http://127.0.0.1:5173/">正常游戏</a> · <a href="../sky-effects-20260907/index.html">之前的天空与轮胎效果记录</a></p>
<script>const compare=document.getElementById('compare');document.getElementById('split').oninput=e=>compare.style.setProperty('--split',e.target.value+'%');for(const name of ['colour-bounce','coated-indirect','indirect','barrier','car'])document.getElementById(name).onclick=()=>{document.getElementById('before').src=name+'-before.png';document.getElementById('after').src=name+'-after.png';};</script></html>`);
console.log(out);
