import fs from 'node:fs/promises';
import crypto from 'node:crypto';
const from='scratch/sky-effects-20260907',to='docs/verification/sky-effects-20260907';
await fs.mkdir(to,{recursive:true});
const images=['sky-original','sky-procedural','sky-hdri','smoke-before','smoke-lit','smoke-shadow-test','smoke-near','marks-before','marks-after','porsche-rear-low','porsche-rear-high','porsche-badge-native-2560','moving-end'];
for(const name of images)await fs.copyFile(`${from}/${name}.png`,`${to}/${name}.png`);
for(const file of ['tire-effects-moving.webm','performance-no-smoke.json','performance-near-smoke.json','porsche-rear-badge-candidates.json'])await fs.copyFile(`${from}/${file}`,`${to}/${file}`);
const no=JSON.parse(await fs.readFile(`${from}/performance-no-smoke.json`)),yes=JSON.parse(await fs.readFile(`${from}/performance-near-smoke.json`));
for(const r of [no,yes])if(r.state!=='race'||String(r.resolution)!=='1280,720'||r.frameRateCap!==null)throw Error('Invalid performance evidence');
const num=n=>n.toFixed(2);
await fs.writeFile(`${to}/index.html`,`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>StreetRush · 天空与轮胎效果小样</title><style>
:root{color-scheme:dark;font-family:system-ui,sans-serif;background:#10171e;color:#e6edf3}*{box-sizing:border-box}body{max-width:1320px;margin:auto;padding:32px 24px 64px}h1{font-size:30px;letter-spacing:-.04em;margin:10px 0}h2{font-size:21px;margin-top:34px}p{color:#afc0cc;line-height:1.7}small{color:#dceb83}nav{display:flex;gap:8px;flex-wrap:wrap;margin:24px 0 16px}button,a.pill{border:1px solid #445765;background:#20303c;color:#dfebf3;border-radius:7px;padding:10px 15px;cursor:pointer;text-decoration:none;font:inherit}button.active{color:#182016;background:#dbea85;border-color:#dbea85}.compare{position:relative;aspect-ratio:16/9;border:1px solid #435563;border-radius:10px;overflow:hidden;--split:50%}.compare img{position:absolute;inset:0;width:100%;height:100%;object-fit:fill}.before{clip-path:inset(0 calc(100% - var(--split)) 0 0)}.bar{position:absolute;left:var(--split);top:0;bottom:0;width:2px;background:white}.tag{position:absolute;top:12px;padding:7px 12px;background:#10171ee8;border-radius:6px;font-size:12px}.tag.old{left:12px}.tag.new{right:12px}input{width:100%;accent-color:#dbea85}a{color:#dbea85}.grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.grid img{width:100%;border-radius:8px}video{width:100%;border:1px solid #435563;border-radius:10px}table{border-collapse:collapse;width:100%}th,td{padding:12px;border-bottom:1px solid #354755;text-align:left}.muted{font-size:13px;color:#93a9b8}.links{display:flex;flex-wrap:wrap;gap:9px}details{margin-top:24px}summary{cursor:pointer;color:#dbea85}@media(max-width:650px){body{padding:24px 12px}.grid{grid-template-columns:1fr}h1{font-size:24px}th,td{font-size:12px;padding:8px}}
</style><small>STREET RUSH / DAYLIGHT & TIRE EFFECTS</small><h1>晴天、轮胎烟与胎痕 · 实机小样</h1><p>保留 HDRI 晴天；修正轮胎烟的形状、消散与受光；胎痕保留沥青颗粒。这里展示游戏直接截图与正常速度录像。</p><nav id="tabs"></nav><div class="compare" id="compare"><img id="after" alt="调整后"><img id="before" class="before" alt="调整前"><div class="bar"></div><span id="oldLabel" class="tag old"></span><span id="newLabel" class="tag new"></span></div><input id="split" aria-label="拖动比较前后" type="range" value="50" min="0" max="100"><p id="caption"></p><p class="muted">天空组统一机位、58° FOV、1.35 渲染比例；轮胎效果组为同一赛道、固定发射样例、固定随机种子。旧效果对照仅禁用陈旧包围体裁剪，使原材质可见；不是未改动的生产回放。</p>
<h2>正常速度的移动检查</h2><video id="movie" controls muted playsinline preload="metadata" poster="moving-end.png" src="tire-effects-moving.webm"></video><div class="links" style="margin-top:12px"><button id="play">播放 / 暂停</button><button data-time="2">查看 2 秒</button><button data-time="4">查看 4 秒</button><button data-time="6">查看 6 秒</button></div><p id="movie-info" class="muted">读取录像信息…</p><p>正常游戏车辆沿起点直线行驶，开发工具持续触发轮胎视觉效果，用于观察移动尾迹、消散和胎痕接续。它没有修改轮胎物理或证明普通刹车必然冒烟；录制与性能采样分开进行。</p>
<h2>烟雾在真实太阳遮挡下</h2><div class="grid"><figure style="margin:0"><img src="smoke-lit.png" alt="阳光下的轮胎烟"><figcaption class="muted">阳光下</figcaption></figure><figure style="margin:0"><img src="smoke-shadow-test.png" alt="遮光板挡住太阳后的轮胎烟"><figcaption class="muted">开发测试遮光板挡住太阳后；光源强度没有改变</figcaption></figure></div><p>烟雾读取同一张太阳阴影图，亮处与阴影处有差异；软粒子读取不透明场景深度，避开车身与地面的硬交线。它在 AO 后、统一色调映射前合成。</p>
<h2>保时捷尾部文字</h2><p>上方“车尾清晰度”比较实际 921×518 和 2560×1440 绘制缓冲，统一显示尺寸。低分辨率会丢掉小字笔画。高清特写可以读出 PORSCHE；字标本身很薄，正常追车距离下只有几像素高。本轮没有修改用户正在调整的车材质文件。</p><p><a href="porsche-rear-high.png">打开 2560×1440 原始车尾帧</a> · <a href="porsche-badge-native-2560.png">打开字标高清特写</a></p>
<h2>有烟 / 无烟的短性能对照</h2><p>Apple M4 · 1280×720 · 同机位、同场景 · 车辆隐藏 · 固定近镜头烟团 · 预热 3 秒、正常刷新率采样 12 秒。测量时恢复正常游戏模拟。</p><table><thead><tr><th>指标</th><th>无烟</th><th>近镜头烟</th></tr></thead><tbody><tr><th>GPU 平均 / ms</th><td>${num(no.gpuMs.mean)}</td><td>${num(yes.gpuMs.mean)}</td></tr><tr><th>GPU P95 / ms</th><td>${num(no.gpuMs.p95)}</td><td>${num(yes.gpuMs.p95)}</td></tr><tr><th>渲染提交 CPU / ms</th><td>${num(no.renderCpuMs.mean)}</td><td>${num(yes.renderCpuMs.mean)}</td></tr><tr><th>绘制次数</th><td>${Math.round(no.drawCalls.mean)}</td><td>${Math.round(yes.drawCalls.mean)}</td></tr><tr><th>整帧平均 / ms</th><td>${num(no.frameMs.mean)}</td><td>${num(yes.frameMs.mean)}</td></tr></tbody></table><p>这组近镜头样例增加约 <b>${num(yes.gpuMs.mean-no.gpuMs.mean)} ms</b> GPU 耗时；不能外推到所有车辆、分辨率或整个画质更新。近镜头样例实际提交 ${yes.effects.particles} 张烟雾面片，估算累计覆盖 ${yes.effects.screenCoverage} 屏；它是重复覆盖面积，不是屏幕不透明比例。</p><p><a href="performance-no-smoke.json">无烟统计</a> · <a href="performance-near-smoke.json">近镜头烟统计</a></p>
<h2>低负载实机入口</h2><div class="links"><a class="pill" href="http://127.0.0.1:5173/?renderreview&reviewcar=gt3rs&reviewview=hero">看天空与车辆</a><a class="pill" href="http://127.0.0.1:5173/?renderreview&reviewdemo=smoke">仅轮胎烟</a><a class="pill" href="http://127.0.0.1:5173/?renderreview&reviewdemo=marks">仅胎痕</a><a class="pill" href="http://127.0.0.1:5173/">正常游戏</a></div><p class="muted">静态小样 5 FPS，并使用已有暂停机制停止车辆模拟；“正常预览”“行驶特效”“测量”临时恢复，结束后自动暂停。正常产品入口不受此预览上限影响。</p><details><summary>方法与素材</summary><p>天空为 Poly Haven <a href="https://polyhaven.com/a/kloofendal_48d_partly_cloudy_puresky">Kloofendal 48d Partly Cloudy (Pure Sky)</a>，Greg Zaal / Jarod Guest，<a href="https://polyhaven.com/license">CC0</a>。2K HDR 原文件 5,451,493 bytes，未修改；太阳方向按高亮像素对齐，PMREM 捕获时压低太阳圆盘的极亮峰值。下载体积不代表 GPU 显存。</p><p>本轮没有新增局部反射探针、级联阴影、整场景体积光或昼夜系统。原场景几何仍比较简化。完整物理验收、真实移动设备和长时间全赛道测试未运行。<a href="source-sha256.json">交付源码校验和</a></p></details>
<script>const choices=[['天空：HDRI','sky-original','sky-hdri','原天空','保留：HDRI 晴天','同机位观察天空层次、车辆高光与路面的关系。'],['天空：程序方案','sky-original','sky-procedural','原天空','程序晴天候选','程序调整仍较单调，因此保留有云层的 HDRI 方案。'],['轮胎烟','smoke-before','smoke-lit','旧轮胎烟材质','新轮胎烟','固定两秒样例。旧版诊断关闭包围体裁剪，保留原粒子形状与消散方式。'],['胎痕','marks-before','marks-after','旧胎痕','新胎痕','固定四秒轨迹，观察边缘、浓淡、白线接续与沥青颗粒。'],['车尾清晰度','porsche-rear-low','porsche-rear-high','921×518 绘制','2560×1440 静态参考','高清帧明确绕过动态分辨率及像素预算，不代表正常入口始终使用这个分辨率。']];const tabs=document.getElementById('tabs');for(const row of choices){const b=document.createElement('button');b.textContent=row[0];b.onclick=()=>{document.getElementById('before').src=row[1]+'.png';document.getElementById('after').src=row[2]+'.png';document.getElementById('oldLabel').textContent=row[3];document.getElementById('newLabel').textContent=row[4];document.getElementById('caption').textContent=row[5];for(const c of tabs.children)c.classList.toggle('active',c===b)};tabs.append(b)}tabs.firstChild.click();document.getElementById('split').oninput=e=>document.getElementById('compare').style.setProperty('--split',e.target.value+'%');const movie=document.getElementById('movie');movie.onloadedmetadata=()=>document.getElementById('movie-info').textContent=movie.videoWidth+'×'+movie.videoHeight+' · '+(Number.isFinite(movie.duration)?movie.duration.toFixed(1)+' 秒':'8 秒录制窗口')+' · Canvas 原始录像，未后期处理';document.getElementById('play').onclick=()=>movie.paused?movie.play():movie.pause();for(const b of document.querySelectorAll('[data-time]'))b.onclick=()=>{movie.pause();movie.currentTime=Number(b.dataset.time);};</script></html>`);
const files=['src/rendering.js','src/render-pipeline.js','src/render-review.js','src/tire-effects.js','src/effects.js','src/main.js','scripts/test-tire-effects.mjs','src/car-materials.js','src/assets.js'];
const hashes=Object.fromEntries(await Promise.all(files.map(async f=>[f,crypto.createHash('sha256').update(await fs.readFile(f)).digest('hex')])));
await fs.writeFile(`${to}/source-sha256.json`,JSON.stringify(hashes,null,2));
console.log(to);
