"""Build the portable HTML presentation from actual exported assets and rendered views."""
import json,html
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
shots=[('01_overall','完整区域','主直道、维修楼、控制室、裁判岗、围界与看台'),('02_driving','驾驶视角','以 1.45m 视点检查道路与沿线设施'),('03_reverse','反向整体','从另一端检查建筑实体与区域关系'),('04_garage','维修楼近景','门洞、卷帘、结构柱、二层栏杆与遮阳檐'),('05_facilities','维修设施近景','工具车、脚轮、抽屉及轮胎架'),('06_surface','路缘与地表','沥青、涂装、斜坡路缘、砾石和草边'),('07_control','控制室与楼梯','观察窗、外部交通、平台和机电设施'),('08_rear','背面与屋顶','完整体量、后立面和屋面设备')]
cards=''.join(f'<figure><a href="previews/{n}.png"><img src="previews/{n}.png" loading="lazy" alt="{t}实际模型渲染"></a><figcaption><b>{t}</b><span>{d}</span></figcaption></figure>' for n,t,d in shots if (ROOT/'previews'/f'{n}.png').exists())
report_path=ROOT/'review'/'export-report.json';report=json.loads(report_path.read_text()) if report_path.exists() else {'assets':[]}
assetrows=''.join(f'<tr><td><a href="{a["file"]}">{html.escape(a["name"])}</a></td><td>{a["triangles"]:,}</td><td>{a["file_bytes"]/1048576:.1f} MB</td><td>{html.escape(a["description"])}</td></tr>' for a in report['assets'])
source=json.loads((ROOT/'sources'/'source-manifest.json').read_text())
materialrows=''.join(f'<tr><td><a href="{a["source"]}">{html.escape(a["title"] or a["id"])}</a></td><td>CC0</td><td>{html.escape(" / ".join(a["authors"]))}</td></tr>' for a in source['sources'])
body='''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>龙湾 · 赛道环境资产集</title>
<style>*{box-sizing:border-box}body{margin:0;background:#151a1c;color:#dce2e0;font:15px/1.7 -apple-system,BlinkMacSystemFont,Arial,sans-serif}main{max-width:1450px;margin:auto;padding:42px 5vw 80px}a{color:#edae8b}header{display:flex;justify-content:space-between;gap:40px;border-bottom:1px solid #485256;padding-bottom:28px;margin-bottom:32px}.eyebrow{color:#df755c;font-size:12px;letter-spacing:.28em}h1{font-size:clamp(34px,5vw,62px);font-weight:500;line-height:1.07;letter-spacing:-.04em;margin:12px 0 22px}header p{max-width:630px;color:#abb7b6}.number{font:100px/1 Georgia;color:#3f4a4e}h2{font-size:25px;font-weight:500;margin:55px 0 20px}.links{display:flex;flex-wrap:wrap;gap:10px}.links a{border:1px solid #697470;padding:10px 18px;text-decoration:none;border-radius:3px}.links .main{color:#fff;background:#b54930;border-color:#b54930}.grid{display:grid;grid-template-columns:1fr 1fr;gap:24px}figure{margin:0;background:#20282b}figure img{display:block;width:100%;height:auto}figcaption{padding:16px 20px}figcaption b{display:block;font-weight:500;font-size:17px}figcaption span{display:block;color:#9cacab;font-size:12px}table{border-collapse:collapse;width:100%;font-size:12px}td,th{text-align:left;vertical-align:top;border-bottom:1px solid #3c494d;padding:11px 12px}th{font-weight:500;color:#c68168}td:last-child{color:#a7b6b5}.wide{grid-column:1/-1}.panel{padding:22px 28px;background:#20282b;border-left:3px solid #b65037}.subtle{color:#a1b1b0}.reference img{aspect-ratio:16/9;object-fit:contain;background:#0e1214}.comparison{display:grid;grid-template-columns:1fr 1fr;gap:20px}.tag{font-size:11px;color:#dda17f;letter-spacing:.10em}footer{margin-top:50px;color:#7f9491;font-size:12px}@media(max-width:780px){.grid,.comparison{grid-template-columns:1fr}.number{display:none}main{padding:24px 20px}.tablewrap{overflow:auto}td:last-child{min-width:250px}}
</style><main><header><div><div class="eyebrow">STREETRUSH / ENVIRONMENT COLLECTION 01</div><h1>LONGWAN<br>PIT EXIT</h1><p>龙湾赛道 · 主直道与维修区出口。围绕一个完整常设赛车场区域制作的建筑、设施、道路边缘与地表资产。现代混凝土、石墨金属、灰蓝玻璃与朱红识别色。</p><div class="links"><a class="main" href="viewer/">实际模型 · 实时查看</a><a href="scene/longwan_pit_exit_editable.blend">可编辑 Blender 场景</a><a href="scene/longwan_pit_exit.glb">组合 GLB</a><a href="README.md">交付说明</a></div></div><div class="number">01</div></header>
<div class="panel">所有下列成果图均由实际模型与材质渲染。模型与材质独立保存，本轮未接入游戏。实时查看需要运行 <code>python3 viewer/serve.py</code>，访问启动地址；本总览可直接双击打开。</div>
<h2>实际模型与材质</h2><div class="grid">'''+cards+'''</div>
<h2>品质参照与成果对照</h2><p class="subtle">以成熟赛车游戏的场景组织、物理尺度、构造层次和材质变化为参照。参照图片属于原作者与权利人，仅用于此私有评估页，未纳入任何可用模型或材质文件。</p>
<div class="comparison"><figure class="reference"><img src="review/reference-hakone.jpg" loading="lazy"><figcaption><span class="tag">REFERENCE / TURN 10</span><b>Forza Motorsport · Hakone Circuit</b><span><a href="https://chrisrojo.com/forza">Chris Rojo 作品集</a> · 团队作品 © Xbox Game Studios</span></figcaption></figure><figure><img src="previews/02_driving.png" loading="lazy"><figcaption><span class="tag">DELIVERED / LONGWAN</span><b>龙湾 · 驾驶视角</b><span>对照赛道边缘、围界层次、设施的轮廓与材质尺度。</span></figcaption></figure><figure class="reference"><img src="review/reference-acc-pit.jpg" loading="lazy"><figcaption><span class="tag">REFERENCE / KUNOS</span><b>Assetto Corsa Competizione · 维修区</b><span><a href="https://assettocorsa.gg/assetto-corsa-competizione/">Kunos 官方画面</a></span></figcaption></figure><figure><img src="previews/04_garage.png" loading="lazy"><figcaption><span class="tag">DELIVERED / LONGWAN</span><b>龙湾 · 维修楼</b><span>对照建筑构造、设施用途、门口作业区与材质细节。</span></figcaption></figure></div>
<p class="panel">实际达到的部分与仍存在的差距以 <a href="review/FINAL_ASSESSMENT.md">最终视觉评估</a> 为准。完整赛车场远景、动态人群、天气变化及游戏目标帧率不属于本次独立区域制作；不宣称与参照作品整体等质。</p>
<h2>独立资产</h2><p class="subtle">每项可单独下载 GLB；可编辑的构件、材质和集合保留在 Blender 场景及源脚本中。GLB 使用米、Y 向上，纹理内嵌。</p><div class="tablewrap"><table><tr><th>模型</th><th>三角面</th><th>文件</th><th>用途与构造</th></tr>'''+assetrows+'''</table></div>
<h2>材质与来源</h2><table><tr><th>原始素材</th><th>许可</th><th>作者</th></tr>'''+materialrows+'''</table><p class="subtle">原文件与 SHA256 清单在 <a href="sources/source-manifest.json">sources/source-manifest.json</a>。派生沥青和自制涂层 PBR 图保留生成源码；未覆盖原始素材。<a href="review/RESOURCE_SELECTION.md">筛选判断与使用说明</a></p>
<h2>过程与验证</h2><div class="links"><a href="review/VISUAL_REVIEW.md">视觉迭代记录</a><a href="previews/r01_overall.png">首轮草稿</a><a href="review/export-report.json">模型清单</a><a href="review/bundle-verification.json">文件验证结果</a><a href="source/build_scene.py">建模源脚本</a></div><footer>LONGWAN / Asset Collection 01 · 2026-09-07 · Independent art delivery · Game integration NOT_RUN</footer></main></html>'''
(ROOT/'index.html').write_text(body,encoding='utf8')
print('Gallery written from existing previews and export manifest')
