#!/usr/bin/env bash
set -euo pipefail

ROOT="/Volumes/Storage/streetrush/research-output/audio-20260907/shared"
ORIG="$ROOT/originals"
EVID="$ROOT/evidence/pages"
mkdir -p "$ORIG" "$EVID"

download() {
  local out="$1"
  local url="$2"
  curl -L --fail --silent --show-error --retry 2 --max-time 120 -o "$ORIG/$out" "$url"
}

page() {
  local out="$1"
  local url="$2"
  curl -L --fail --silent --show-error --retry 2 --max-time 60 -o "$EVID/$out.html" "$url"
}

# Kenney CC0 audio bundles; retain the original ZIPs and select a few files later.
download "kenney_interface-sounds.zip" "https://kenney.nl/media/pages/assets/interface-sounds/fa43c1dd4d-1677589452/kenney_interface-sounds.zip"
download "kenney_impact-sounds.zip" "https://kenney.nl/media/pages/assets/impact-sounds/87b4ddecda-1677589768/kenney_impact-sounds.zip"

# OpenGameArt CC0 / CC-BY files and small packs.
download "generic_car_startengine.wav" "https://opengameart.org/sites/default/files/generic_car_startengine.wav"
download "generic_car_startengine_1.wav" "https://opengameart.org/sites/default/files/generic_car_startengine_1.wav"
download "engine_start_up_01.wav" "https://opengameart.org/sites/default/files/engine_start_up_01.wav"
download "door_opening.wav" "https://opengameart.org/sites/default/files/door_opening.wav"
download "door_closing.wav" "https://opengameart.org/sites/default/files/door_closing.wav"
download "blinker01.wav" "https://opengameart.org/sites/default/files/blinker01.wav"
download "carskid.7z" "https://opengameart.org/sites/default/files/carskid.7z"
download "car_sound_effects_pack.zip" "https://opengameart.org/sites/default/files/car_sound_effects_pack.zip"
download "racing_loop_0.wav" "https://opengameart.org/sites/default/files/loop_0.wav"
download "racing_loop_3.wav" "https://opengameart.org/sites/default/files/loop_3.wav"
download "high_traffic_road.ogg" "https://opengameart.org/sites/default/files/gatve%20Varniu.ogg"
download "car1_moving.wav" "https://opengameart.org/sites/default/files/car1.wav"
download "short_wind_sound.wav" "https://opengameart.org/sites/default/files/short%20wind%20sound.wav"
download "wind.zip" "https://opengameart.org/sites/default/files/wind.zip"
download "birdchirping071414.mp3" "https://opengameart.org/sites/default/files/birdchirping071414.mp3"
download "birds_isaiah658.ogg" "https://opengameart.org/sites/default/files/birds-isaiah658.ogg"
download "crowd_shouting.ogg" "https://opengameart.org/sites/default/files/crowd_shouting.ogg"
download "applause_clapping_church_crowd.wav" "https://opengameart.org/sites/default/files/applause-clapping-church-crowd-immersive.wav"
download "metal_bing1.wav" "https://opengameart.org/sites/default/files/bing1.wav"
download "metal_clink2.wav" "https://opengameart.org/sites/default/files/clink2.wav"
download "metal_thud2.wav" "https://opengameart.org/sites/default/files/thud2.wav"
download "glass_breaking.wav" "https://opengameart.org/sites/default/files/glass_breaking.wav"
download "mechanical_clank1.wav" "https://opengameart.org/sites/default/files/clank1.wav"
download "mechanical_lightclunk1.wav" "https://opengameart.org/sites/default/files/lightclunk1.wav"
download "mechanical_rattle1.wav" "https://opengameart.org/sites/default/files/rattle1.wav"
download "different_steps.zip" "https://opengameart.org/sites/default/files/%5Bkdd%5DDifferentSteps_0.zip"
download "100-CC0-wood-metal-SFX.zip" "https://opengameart.org/sites/default/files/100-CC0-wood-metal-SFX.zip"
download "supertuxkart_sfx.mp3" "https://opengameart.org/sites/default/files/sfx%20kart%20game_0.mp3"
download "race_countdown.ogg" "https://opengameart.org/sites/default/files/countdown.ogg"
download "well_done.ogg" "https://opengameart.org/sites/default/files/Well%20Done%20CCBY3.ogg"
download "game_over.ogg" "https://opengameart.org/sites/default/files/GameOver.ogg"
download "beep.wav" "https://opengameart.org/sites/default/files/beep.wav"

# Save the source pages used for the catalog and license audit.
page "kenney_interface_sounds" "https://kenney.nl/assets/interface-sounds"
page "kenney_impact_sounds" "https://kenney.nl/assets/impact-sounds"
page "kenney_support" "https://kenney.nl/support"
page "oga_car_engine_start_01" "https://opengameart.org/content/car-engine-start-01"
page "oga_car_engine_start_02" "https://opengameart.org/content/car-engine-start-up-02"
page "oga_car_door_sfx" "https://opengameart.org/content/cardoorsfx"
page "oga_car_blinker_sfx" "https://opengameart.org/content/car-blinker-sfx"
page "oga_car_tire_skid" "https://opengameart.org/content/car-tire-skid-squealing"
page "oga_car_sound_pack" "https://opengameart.org/content/car-sound-effects-pack-low-quality"
page "oga_racing_engine_loops" "https://opengameart.org/content/racing-car-engine-sound-loops"
page "oga_high_traffic_road" "https://opengameart.org/content/high-traffic-road-sounds"
page "oga_car_1" "https://opengameart.org/content/car-1-1"
page "oga_short_wind" "https://opengameart.org/content/short-wind-sound"
page "oga_wind" "https://opengameart.org/content/wind"
page "oga_bird_chirping" "https://opengameart.org/content/bird-chirping-sounds"
page "oga_ambient_birds" "https://opengameart.org/content/ambient-bird-sounds"
page "oga_crowd" "https://opengameart.org/content/crowd-shoutingspeaking-ambience"
page "oga_applause" "https://opengameart.org/content/applause-in-a-large-hall-or-church"
page "oga_metal_impact" "https://opengameart.org/content/metal-impact-sounds"
page "oga_glass_break" "https://opengameart.org/content/glass-break"
page "oga_mechanical_sounds" "https://opengameart.org/content/mechanical-sounds"
page "oga_gravel_steps" "https://opengameart.org/content/different-steps-on-wood-stone-leaves-gravel-and-mud"
page "oga_metal_wood_pack" "https://opengameart.org/content/100-cc0-metal-and-wood-sfx"
page "oga_supertuxkart_sfx" "https://opengameart.org/content/supertuxkart-sound-effects"
page "oga_race_countdown" "https://opengameart.org/content/race-start-countdown"
page "oga_well_done" "https://opengameart.org/content/well-done"
page "oga_game_over" "https://opengameart.org/content/game-over-soundold-school"
page "oga_beep_tone" "https://opengameart.org/content/beep-tone-sound-sfx"

date -u +%Y-%m-%dT%H:%M:%SZ > "$ROOT/evidence/acquired_at_utc.txt"
